config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: /.*/ do
    resources :medics
  end

  resources :hospitals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hospital.rb
class Hospital < ApplicationRecord
end

app/models/medic.rb
class Medic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: %i[ show edit update destroy ]

  # GET /hospitals or /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1 or /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals or /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully created." }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1 or /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to hospital_url(@hospital), notice: "Hospital was successfully updated." }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1 or /hospitals/1.json
  def destroy
    @hospital.destroy

    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: "Hospital was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:slug, :name, :description)
    end
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  before_action :set_medic, only: %i[ show edit update destroy ]
  before_action :set_hospitals, only: [:edit, :update, :new, :create]

  # GET /medics or /medics.json
  def index
    @medics = Medic.where(tenant_id: @hospitals.id)
  end

  # GET /medics/1 or /medics/1.json
  def show
  end

  # GET /medics/new
  def new
    @medic = Medic.new
  end

  # GET /medics/1/edit
  def edit
  end

  # POST /medics or /medics.json
  def create
    @medic = Medic.new(medic_params)

    respond_to do |format|
      if @medic.save
        format.html { redirect_to medic_url(@medic), notice: "Medic was successfully created." }
        format.json { render :show, status: :created, location: @medic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medics/1 or /medics/1.json
  def update
    respond_to do |format|
      if @medic.update(medic_params)
        format.html { redirect_to medic_url(@medic), notice: "Medic was successfully updated." }
        format.json { render :show, status: :ok, location: @medic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medics/1 or /medics/1.json
  def destroy
    @medic.destroy

    respond_to do |format|
      format.html { redirect_to medics_url, notice: "Medic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medic
      @medic = Medic.find_by!(id: params[:id], tenant_id: @hospitals.id)
    end

    # Only allow a list of trusted parameters through.
    def medic_params
      params.require(:medic).permit(:name, :specialty, :tenant_id)
    end

    def set_hospitals
     @hospitals = Hospital.find_by!(slug: request.subdomain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medics_helper.rb
module MedicsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital) do |form| %>
  <% if hospital.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hospitals/_hospital.html.erb
<div id="<%= dom_id hospital %>">
  <p>
    <strong>Slug:</strong>
    <%= hospital.slug %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= hospital.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hospital.description %>
  </p>

</div>

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Show this hospital", @hospital %> |
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hospitals</h1>

<div id="hospitals">
  <% @hospitals.each do |hospital| %>
    <%= render hospital %>
    <p>
      <%= link_to "Show this hospital", hospital %>
    </p>
  <% end %>
</div>

<%= link_to "New hospital", new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render "form", hospital: @hospital %>

<br>

<div>
  <%= link_to "Back to hospitals", hospitals_path %>
</div>

app/views/hospitals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hospital %>

<div>
  <%= link_to "Edit this hospital", edit_hospital_path(@hospital) %> |
  <%= link_to "Back to hospitals", hospitals_path %>

  <%= button_to "Destroy this hospital", @hospital, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/medics/_form.html.erb
<%= form_with(model: medic) do |form| %>
  <% if medic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medic.errors.count, "error") %> prohibited this medic from being saved:</h2>

      <ul>
        <% medic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :specialty, style: "display: block" %>
    <%= form.text_field :specialty %>
  </div>

  <div className="field">
    <%= form.label :hospital %>
    <%= form.select :tenant_id, options_from_collection_for_select(@hospitals, 'id', 'name', medic.tenant_id), include_blank: true %>
  </div>

  <%= form.hidden_field :tenant_id, value: @hospitals.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medics/_medic.html.erb
<div id="<%= dom_id medic %>">
  <p>
    <strong>Name:</strong>
    <%= medic.name %>
  </p>

  <p>
    <strong>Specialty:</strong>
    <%= medic.specialty %>
  </p>

</div>

app/views/medics/edit.html.erb
<h1>Editing medic</h1>

<%= render "form", medic: @medic %>

<br>

<div>
  <%= link_to "Show this medic", @medic %> |
  <%= link_to "Back to medics", medics_path %>
</div>

app/views/medics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medics</h1>

<div id="medics">
  <% @medics.each do |medic| %>
    <%= render medic %>
    <p>
      <%= link_to "Show this medic", medic %>
    </p>
  <% end %>
</div>

<%= link_to "New medic", new_medic_path %>

app/views/medics/new.html.erb
<h1>New medic</h1>

<%= render "form", medic: @medic %>

<br>

<div>
  <%= link_to "Back to medics", medics_path %>
</div>

app/views/medics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medic %>

<div>
  <%= link_to "Edit this medic", edit_medic_path(@medic) %> |
  <%= link_to "Back to medics", medics_path %>

  <%= button_to "Destroy this medic", @medic, method: :delete %>
</div>